# docs: https://docs.docker.com/reference/compose-file/
name: pmwiki-bibtexpages-compose
services:
  pmwiki:
    container_name: pmwiki-bibtexpages-ctr
    image: pmwiki-bibtexpages-img
    build:
      # context dir used in image build as root path for paths in Dockerfile
      # Path relative to this file.
      # https://docs.docker.com/reference/compose-file/build/#context
      context: ../
      # build with this Dockerfile ( path specified from context dir)
      # https://docs.docker.com/reference/compose-file/build/#dockerfile
      dockerfile: .devcontainer/pmwiki/Dockerfile
      # uncomment next lines to change params used in Dockerfile to build pmwiki image
      args:
        PMWIKI_VERSION: "2.3.37" # newest version of pmwiki, not working with markup_e
      #   PMWIKI_VERSION: '2.3.9' # old version still working with markup_e
      #   PMWIKI_DIR: '/var/www/html/pmwiki' # install pmwiki in subdir
    ports:
      # - "80:80"    # does NOT need vmnetd service(macos), but needs NET_BIND_SERVICE
      # - "443:443"  # does NOT need vmnetd service(macos), but needs NET_BIND_SERVICE
      # - "127.0.0.1:80:80" # needs NET_BIND_SERVICE and needs vmnetd service(macos) running because priviliged port to specific interface
      # - "127.0.0.1:443:443" # needs NET_BIND_SERVICE and needs vmnetd service(macos) running because priviliged port to specific interface
      - "127.0.0.1:8080:80" # does NOT need vmnetd service(macos) nor NET_BIND_SERVICE (because none-priviliged port)
      - "127.0.0.1:8443:443" # does NOT need vmnetd service(macos) nor NET_BIND_SERVICE (because none-priviliged port)
    # cap_add:
    #  - NET_BIND_SERVICE
    environment:
      - COOKBOOK=bibtexpages
    # We run service as root user because in normal linux distributions the apache daemon is started
    # as root and then handles http requests with www-data user by spinning of daemons using that user. 
    # We do not run the container as www-data because that would be different from how normally the apache server is started.
    # So next line is commented out (default "user:root")
    #user: "www-data"
    # background info:
    # https://docs.docker.com/reference/compose-file/services/#user
    # https://docs.docker.com/reference/dockerfile/#user
    #
    # Volumes:
    # - we bind pwmiki subfolders from repository in pmwiki folder. (by default gets owned by user root because container is run as root)
    # - we bind the root of this repository in the _GIT_REPO_COOKBOOK subfolder of the pmwiki folder used as workspace folder in the devcontainer,
    #   so that we can do git commits to the git repository from within the devcontainer.
    #   Vscode automatically detects all git repositories with a .git directory in the workspace folder or subdirectories.
    # In devcontainer.json vscode attaches itself as www-data user (remoteUser), and it uses the postStartCommand to make 
    # sure all subfolders a owned by www-data user so that gitrepo is directly trusted by vscode.
    volumes:
      - type: bind
        source: ../data/wiki.d/
        target: /var/www/html/pmwiki/wiki.d/
      - type: bind
        source: ../data/uploads/
        target: /var/www/html/pmwiki/uploads/
      - type: bind
        source: ../data/local/
        target: /var/www/html/pmwiki/local/
      - type: bind
        source: ../data/cookbook/bibtexpages
        target: /var/www/html/pmwiki/cookbook/bibtexpages
      - type: bind
        source: ../data/pub/bibtexpages
        target: /var/www/html/pmwiki/pub/bibtexpages
      - type: bind
        source: ../
        target: /var/www/html/pmwiki/_GIT_REPO_COOKBOOK
